/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.Koneksi;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author coyha
 */
public class MenuLeave extends javax.swing.JPanel {

    private Connection conn = new Koneksi().connect();

    Integer karyawan_id;
    String role;

    public MenuLeave() {
        initComponents();
        loadData();
    }

    public MenuLeave(Integer karyawanId, String role) {
        this.karyawan_id = karyawanId;
        this.role = role;
        initComponents();

        if (role.toLowerCase().equals("user")) {
            btnApprove.setVisible(false);
            btnReject.setVisible(false);
        }
        else {
            btnAdd.setVisible(false);
        }
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 91, 99));
        jLabel1.setText("Pengajuan Cuti");

        jScrollPane5.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setBackground(new java.awt.Color(0, 91, 99));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Buat Pengajuan");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "NIP", "Nama", "Tanggal Pengajuan", "Tanggal Mulai", "Tanggal Selesai", "Alasan", "Status"
            }
        ));
        tblKaryawan.setRowHeight(40);
        tblKaryawan.setSelectionBackground(new java.awt.Color(230, 244, 241));
        tblKaryawan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        btnEdit.setBackground(new java.awt.Color(0, 91, 99));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Pengajuan");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Hapus Pengajuan");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnApprove.setBackground(new java.awt.Color(0, 91, 99));
        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(255, 51, 51));
        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApprove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReject)))
                        .addGap(0, 430, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(804, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DialogLeaveAddEdit dialog = setupDialog();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tblKaryawan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }
        
        if (!checkStatusCuti(tblKaryawan.getValueAt(row, 0).toString(), "edit")) {
            return;
        }

        DialogLeaveAddEdit dialog = setupDialog();
        String kode = tblKaryawan.getValueAt(row, 0).toString();
        String nip = tblKaryawan.getValueAt(row, 1).toString();
        String tglPengajuan = tblKaryawan.getValueAt(row, 3).toString();
        String tglMulai = tblKaryawan.getValueAt(row, 4).toString();
        String tglSelesai = tblKaryawan.getValueAt(row, 5).toString();
        String alasan = tblKaryawan.getValueAt(row, 6).toString();
        dialog.setData(kode, nip, tglPengajuan, tglMulai, tglSelesai, alasan);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblKaryawan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }
        String kode = tblKaryawan.getValueAt(row, 0).toString();

        if (!checkStatusCuti(kode, "hapus")) {
            return;
        }

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Konfirmasi hapus data?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM cuti WHERE id = '" + kode + "'";
            try {
                Statement stat = conn.createStatement();
                stat.executeUpdate(sql);

                loadData();

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus " + e);
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private boolean checkStatusCuti(String kode, String Action) {

        try {
            // Cek status cuti terlebih dahulu
            String checkSql = "SELECT status FROM cuti WHERE id = ?";
            PreparedStatement checkStat = conn.prepareStatement(checkSql);
            checkStat.setString(1, kode);
            ResultSet rs = checkStat.executeQuery();

            if (rs.next()) {
                String status = rs.getString("status");

                if (!status.equalsIgnoreCase("NEW")) {
                    JOptionPane.showMessageDialog(null, "Hanya data dengan status NEW yang dapat di" + Action);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan.");
                return false;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus: " + e.getMessage());
        }
        return true;
    }
    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tblKaryawan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }
        String kode = tblKaryawan.getValueAt(row, 0).toString();
        
        if (!checkStatusCuti(tblKaryawan.getValueAt(row, 0).toString(), "approve")) {
            return;
        }
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Konfirmasi Approve data?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String sql = "UPDATE cuti SET status = 'APPROVED' WHERE id =  '" + kode + "'";
            try {
                Statement stat = conn.createStatement();
                stat.executeUpdate(sql);

                loadData();

                JOptionPane.showMessageDialog(null, "Data Berhasil DiApprove");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal DiApprove " + e);
            }
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = tblKaryawan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu");
            return;
        }
        String kode = tblKaryawan.getValueAt(row, 0).toString();
        
        if (!checkStatusCuti(tblKaryawan.getValueAt(row, 0).toString(), "reject")) {
            return;
        }
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Konfirmasi Reject data?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String sql = "UPDATE cuti SET status = 'REJECTED' WHERE id =  '" + kode + "'";
            try {
                Statement stat = conn.createStatement();
                stat.executeUpdate(sql);

                loadData();

                JOptionPane.showMessageDialog(null, "Data Berhasil DiReject");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal DiReject " + e);
            }
        }
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblKaryawan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        String sql;

        if (role.toLowerCase().equals("user")) {
            sql = "SELECT c.id,c.karyawan_id,c.tanggal_pengajuan,c.tanggal_mulai,c.tanggal_selesai,c.alasan,c.status,k.nip,k.nama"
                    + " FROM cuti c left join karyawan k on k.id = c.karyawan_id "
                    + " WHERE c.karyawan_id = '" + this.karyawan_id.toString() + "' "
                    + " ORDER BY id DESC";
        } else {
            sql = "SELECT c.id,c.karyawan_id,c.tanggal_pengajuan,c.tanggal_mulai,c.tanggal_selesai,c.alasan,c.status,k.nip,k.nama"
                    + " FROM cuti c left join karyawan k on k.id = c.karyawan_id "
                    + " ORDER BY id DESC";
        }
        Object[] Baris = {
            "id	",
            "NIP",
            "Nama",
            "Tanggal Pengajuan",
            "Tanggal Mulai",
            "Tanggal Selesai",
            "Alasan",
            "Status"
        };

        DefaultTableModel tabModel = new DefaultTableModel(null, Baris) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblKaryawan.setModel(tabModel);

        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int num = 1;

            while (hasil.next()) {
                String[] data = {
                    hasil.getString("id"),
                    hasil.getString("nip"),
                    hasil.getString("nama"),
                    hasil.getString("tanggal_pengajuan"),
                    hasil.getString("tanggal_mulai"),
                    hasil.getString("tanggal_selesai"),
                    hasil.getString("alasan"),
                    hasil.getString("status")
                };

                tabModel.addRow(data);
                num++;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error saat memuat data penilaian karyawan:\n" + e.getMessage());
        }
    }

    private DialogLeaveAddEdit setupDialog() {
        DialogLeaveAddEdit dialog = new DialogLeaveAddEdit(null, true, karyawan_id);
        dialog.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {

            }

            @Override
            public void windowClosing(WindowEvent e) {

            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadData();
            }

            @Override
            public void windowIconified(WindowEvent e) {

            }

            @Override
            public void windowDeiconified(WindowEvent e) {

            }

            @Override
            public void windowActivated(WindowEvent e) {

            }

            @Override
            public void windowDeactivated(WindowEvent e) {

            }
        });
        return dialog;
    }

}
