/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Koneksi.Koneksi;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JFrame;

/**
 *
 * @author coyha
 */
public class MenuHome extends javax.swing.JPanel {

    /**
     * Creates new form MenuHome
     */
    private Connection conn = new Koneksi().connect();
    
    public MenuHome() {
        initComponents();
    }
    
     public MenuHome(String fullname) {
        initComponents();
        jLabel2.setText("Selamat Datang, " + fullname + "!");
        int totalKaryawan = countData(conn, "karyawan");
        int totalCuti = countData(conn, "cuti");
        int totalAbsensi = countData(conn, "absensi");
        int totalResign = countData(conn, "resign");
        
        totKaryawan.setText(String.valueOf(totalKaryawan));
        totCuti.setText(String.valueOf(totalCuti));
        totAbsensi.setText(String.valueOf(totalAbsensi));
        totResign.setText(String.valueOf(totalResign));
        
        setTanggal();
    }
    private void setTanggal() {
        Locale indo = new Locale("id", "ID"); // Lokalisasi Indonesia
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy", indo);
        String tanggalSekarang = sdf.format(new java.util.Date());
        txtTanggal.setText(tanggalSekarang);
    }
     
    public static int countData(Connection conn, String tableName) {
        String sql = "SELECT COUNT(*) FROM " + tableName;

        try (PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            if (rs.next()) {
                return rs.getInt(1);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totKaryawan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totAbsensi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        totCuti = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        totResign = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 91, 99));
        jLabel2.setText("Selamat Datang");

        jPanel1.setBackground(new java.awt.Color(37, 150, 190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Karyawan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 50));

        totKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        totKaryawan.setText("Karyawan");
        jPanel1.add(totKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 82, 40));
        totKaryawan.getAccessibleContext().setAccessibleName("totKaryawan");

        jPanel2.setBackground(new java.awt.Color(255, 193, 7));
        jPanel2.setPreferredSize(new java.awt.Dimension(242, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Absensi");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        totAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totAbsensi.setForeground(new java.awt.Color(255, 255, 255));
        totAbsensi.setText("Karyawan");
        jPanel2.add(totAbsensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 82, -1));
        totAbsensi.getAccessibleContext().setAccessibleName("totAbsensi");

        jPanel3.setBackground(new java.awt.Color(40, 167, 69));
        jPanel3.setPreferredSize(new java.awt.Dimension(242, 77));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totCuti.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totCuti.setForeground(new java.awt.Color(255, 255, 255));
        totCuti.setText("Karyawan");
        jPanel3.add(totCuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 82, 40));
        totCuti.getAccessibleContext().setAccessibleName("totCuti");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cuti");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 50));

        jPanel4.setBackground(new java.awt.Color(220, 53, 69));
        jPanel4.setPreferredSize(new java.awt.Dimension(242, 77));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Resign");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 40));

        totResign.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totResign.setForeground(new java.awt.Color(255, 255, 255));
        totResign.setText("Karyawan");
        jPanel4.add(totResign, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 82, 40));
        totResign.getAccessibleContext().setAccessibleName("totResign");

        txtTanggal.setBackground(new java.awt.Color(0, 153, 153));
        txtTanggal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtTanggal.setForeground(new java.awt.Color(0, 91, 99));
        txtTanggal.setText("Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(456, 456, 456)
                        .addComponent(txtTanggal))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal))
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel totAbsensi;
    private javax.swing.JLabel totCuti;
    private javax.swing.JLabel totKaryawan;
    private javax.swing.JLabel totResign;
    private javax.swing.JLabel txtTanggal;
    // End of variables declaration//GEN-END:variables
}
