/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menu;

import Koneksi.Koneksi;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;

/**
 *
 * @author User
 */
public class MenuAbsensi extends javax.swing.JPanel {

    /**
     * Creates new form MenuAbsensi
     */
    private Connection conn = new Koneksi().connect();
    public DefaultTableModel tabModel;
    List<Integer> listID = new ArrayList<>();

    Integer karyawan_id;

    public MenuAbsensi() {
        initComponents();
    }

    public MenuAbsensi(String fullname, Integer karyawan_id) {
        initComponents();

        this.karyawan_id = karyawan_id;
        jLabel1.setText("Hai, " + fullname);
        startTimer();
        setTanggal();
        loadDataAbsen();
    }

    private void startTimer() {
        Timer timer = new Timer(1000, e -> {
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            String waktu = sdf.format(new Date());
            lblJam.setText(waktu);
        });
        timer.start();
    }

    private void setTanggal() {
        Locale indo = new Locale("id", "ID"); // Lokalisasi Indonesia
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy", indo);
        String tanggalSekarang = sdf.format(new Date());
        lblTanggal.setText(tanggalSekarang);
    }

    private void loadDataAbsen() {
        listID = new ArrayList<Integer>();

        // Query JOIN ke karyawan untuk ambil NIP dan Nama
        String sql = "SELECT a.id, k.nip, k.nama, a.tanggal, a.waktu_masuk, a.waktu_keluar, a.status "
                + "FROM absensi a "
                + "LEFT JOIN karyawan k ON a.karyawan_id = k.id "
                + "WHERE a.status = 'Hadir' AND a.karyawan_id = '" + this.karyawan_id.toString() + "' "
                + "ORDER BY a.tanggal DESC";

        Object[] Baris = {
            "No",
            "NIP",
            "Nama",
            "Tanggal Kehadiran",
            "Jam Masuk",
            "Jam Pulang",
            "Status"
        };

        tabModel = new DefaultTableModel(null, Baris) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblAbsensi.setModel(tabModel);

        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int num = 1;

            while (hasil.next()) {
                String[] data = {
                    Integer.toString(num),
                    hasil.getString("nip"),
                    hasil.getString("nama"),
                    hasil.getString("tanggal"),
                    hasil.getString("waktu_masuk"),
                    hasil.getString("waktu_keluar"),
                    hasil.getString("status")
                };

                tabModel.addRow(data);
                listID.add(hasil.getInt("id"));
                num++;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error saat memuat data absensi:\n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JToggleButton();
        btnPulang = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbsensi = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1264, 607));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 91, 99));
        jLabel1.setText("Halo, [Nama]!");

        btnMasuk.setBackground(new java.awt.Color(51, 153, 0));
        btnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnMasuk.setText("MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        btnPulang.setBackground(new java.awt.Color(255, 0, 0));
        btnPulang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPulang.setForeground(new java.awt.Color(255, 255, 255));
        btnPulang.setText("PULANG");
        btnPulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulangActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 91, 99));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblTanggal.setBackground(new java.awt.Color(241, 222, 201));
        lblTanggal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setText("Rabu, 14 Mei 2025");

        lblJam.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblJam.setForeground(new java.awt.Color(255, 255, 255));
        lblJam.setText("17:06:23");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJam))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        tblAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Tanggal Kehadiran", "Jam Masuk", "Jam Pulang", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAbsensi.setSelectionBackground(new java.awt.Color(230, 244, 241));
        jScrollPane1.setViewportView(tblAbsensi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Riwayat Presensi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPulang, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPulang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        try {
            String status = "Hadir";
            LocalDate today = LocalDate.now();
            LocalTime now = LocalTime.now();

            // Cek apakah sudah absen hari ini
            String checkSql = "SELECT * FROM absensi WHERE karyawan_id = ? AND tanggal = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                checkStmt.setInt(1, karyawan_id);
                checkStmt.setDate(2, java.sql.Date.valueOf(today));
                try (ResultSet rs = checkStmt.executeQuery()) {
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Anda sudah absen masuk hari ini.");
                        return; // berhenti kalau sudah absen
                    }
                }
            }

            // Simpan absensi masuk
            String insertSql = "INSERT INTO absensi (karyawan_id, tanggal, waktu_masuk, status) VALUES (?, ?, ?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                insertStmt.setInt(1, karyawan_id);
                insertStmt.setDate(2, java.sql.Date.valueOf(today));
                insertStmt.setTime(3, java.sql.Time.valueOf(now));
                insertStmt.setString(4, status);

                insertStmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Absen masuk berhasil.");
            }

            loadDataAbsen(); // Refresh data tabel absensi jika ada
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat absen masuk:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnPulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulangActionPerformed
        // TODO add your handling code here:
        try {
            int karyawanId = this.karyawan_id;
            
            LocalDate today = LocalDate.now();
            LocalTime now = LocalTime.now();

            // Cek apakah sudah absen masuk hari ini
            String checkSql = "SELECT * FROM absensi WHERE karyawan_id = ? AND tanggal = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkSql);
            checkStmt.setInt(1, karyawanId);
            checkStmt.setDate(2, java.sql.Date.valueOf(today));
            ResultSet rs = checkStmt.executeQuery();

            if (rs.next()) {
                Time waktuPulang = rs.getTime("waktu_keluar");

                if (waktuPulang != null) {
                    JOptionPane.showMessageDialog(this, "Anda sudah absen pulang hari ini.");
                } else {
                    // Update waktu_keluar
                    String updateSql = "UPDATE absensi SET waktu_keluar = ? WHERE karyawan_id = ? AND tanggal = ?";
                    PreparedStatement updateStmt = conn.prepareStatement(updateSql);
                    updateStmt.setTime(1, java.sql.Time.valueOf(now));
                    updateStmt.setInt(2, karyawanId);
                    updateStmt.setDate(3, java.sql.Date.valueOf(today));

                    updateStmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Absen pulang berhasil.");
                    loadDataAbsen(); // Jika kamu ingin refresh tabel absen
                }
            } else {
                JOptionPane.showMessageDialog(this, "Anda belum absen masuk hari ini.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat absen pulang:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnPulangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMasuk;
    private javax.swing.JToggleButton btnPulang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblAbsensi;
    // End of variables declaration//GEN-END:variables
}
