/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Auth.LoginForm;
import Koneksi.Koneksi;
import Menu.MenuAbsensi;
import Menu.MenuEmployee;
import Menu.MenuEmployeeAssesment;
import Menu.MenuHome;
import Menu.MenuLeave;
import Menu.MenuPayroll;
import Menu.MenuResign;
//import Menu.MenuDivisiProduk;
//import Menu.MenuHome;
//import Menu.MenuKriteria;
//import Menu.MenuPerhitunganDivisiProduk;
//import Menu.MenuPerhitunganKriteria;
//import Menu.MenuPerhitunganSubKriteria;
import javax.swing.JFrame;
import javax.swing.*;
import employeemanagementjava.*;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author coyha
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Connection conn = new Koneksi().connect();
    String fullName = "";
    String roleName = "";
    Integer karyawan_id;

    public MainPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        groupLaporanMouseClicked(null);
    }

    public MainPage(Integer karyawan_id, String fullname, String role) {
        initComponents();
        this.karyawan_id = karyawan_id;
        this.fullName = fullname;
        this.roleName = role;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        groupLaporanMouseClicked(null);

        if (role.toLowerCase().equals("user")) {
            //menuDashboard.setVisible(false);
            MenuEmployee.setVisible(false);
            groupLaporan.setVisible(false);
            MenuResign1.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new RoundedPanel(20, new java.awt.Color(25,100,126));
        MenuEmployee = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MenuLeave = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MenuResign = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        groupLaporan = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        menuLaporanAbsensi = new RoundedPanel(15, new java.awt.Color(109, 152, 186));
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        menuLaporanKaryawan = new RoundedPanel(15, new java.awt.Color(109, 152, 186));
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        menuLaporanCuti = new RoundedPanel(15, new java.awt.Color(109, 152, 186));
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        menuLaporanResign = new RoundedPanel(15, new java.awt.Color(109, 152, 186));
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        menuLaporanPayroll = new RoundedPanel(15, new java.awt.Color(109, 152, 186));
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btnLogout = new RoundedPanel(10, new java.awt.Color(255,153,153));
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        menuAbsensi = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MenuResign1 = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        MenuResign2 = new RoundedPanel(10, new java.awt.Color(109, 152, 186));
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        panelWrapper = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelContent = new RoundedPanel(20, new java.awt.Color(255,255,255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 162, 161));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(241, 245, 249));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 697));

        jLabel1.setBackground(new java.awt.Color(241, 245, 249));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_linkit_hi_icon.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 60));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 25));

        jPanel1.setBackground(new java.awt.Color(101, 67, 33));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 570));

        MenuEmployee.setBackground(new java.awt.Color(0, 162, 161));
        MenuEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuEmployee.setOpaque(false);
        MenuEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEmployeeMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_produk.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Employee");

        javax.swing.GroupLayout MenuEmployeeLayout = new javax.swing.GroupLayout(MenuEmployee);
        MenuEmployee.setLayout(MenuEmployeeLayout);
        MenuEmployeeLayout.setHorizontalGroup(
            MenuEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuEmployeeLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuEmployeeLayout.setVerticalGroup(
            MenuEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuLeave.setBackground(new java.awt.Color(0, 162, 161));
        MenuLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuLeave.setOpaque(false);
        MenuLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLeaveMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sub.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Leave Request");

        javax.swing.GroupLayout MenuLeaveLayout = new javax.swing.GroupLayout(MenuLeave);
        MenuLeave.setLayout(MenuLeaveLayout);
        MenuLeaveLayout.setHorizontalGroup(
            MenuLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLeaveLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuLeaveLayout.setVerticalGroup(
            MenuLeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuResign.setBackground(new java.awt.Color(0, 162, 161));
        MenuResign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuResign.setOpaque(false);
        MenuResign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuResignMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sub.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Resignation");

        javax.swing.GroupLayout MenuResignLayout = new javax.swing.GroupLayout(MenuResign);
        MenuResign.setLayout(MenuResignLayout);
        MenuResignLayout.setHorizontalGroup(
            MenuResignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuResignLayout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuResignLayout.setVerticalGroup(
            MenuResignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        groupLaporan.setBackground(new java.awt.Color(0, 162, 161));
        groupLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groupLaporan.setOpaque(false);
        groupLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupLaporanMouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_report.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Report");

        menuLaporanAbsensi.setBackground(new java.awt.Color(1, 113, 122));
        menuLaporanAbsensi.setOpaque(false);
        menuLaporanAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanAbsensiMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Report Absensi");

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_circle.png"))); // NOI18N

        javax.swing.GroupLayout menuLaporanAbsensiLayout = new javax.swing.GroupLayout(menuLaporanAbsensi);
        menuLaporanAbsensi.setLayout(menuLaporanAbsensiLayout);
        menuLaporanAbsensiLayout.setHorizontalGroup(
            menuLaporanAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanAbsensiLayout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLaporanAbsensiLayout.setVerticalGroup(
            menuLaporanAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        menuLaporanKaryawan.setBackground(new java.awt.Color(1, 113, 122));
        menuLaporanKaryawan.setOpaque(false);
        menuLaporanKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanKaryawanMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Report Karyawan");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_circle.png"))); // NOI18N

        javax.swing.GroupLayout menuLaporanKaryawanLayout = new javax.swing.GroupLayout(menuLaporanKaryawan);
        menuLaporanKaryawan.setLayout(menuLaporanKaryawanLayout);
        menuLaporanKaryawanLayout.setHorizontalGroup(
            menuLaporanKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanKaryawanLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLaporanKaryawanLayout.setVerticalGroup(
            menuLaporanKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLaporanKaryawanLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuLaporanCuti.setBackground(new java.awt.Color(1, 113, 122));
        menuLaporanCuti.setOpaque(false);
        menuLaporanCuti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanCutiMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Report Cuti");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_circle.png"))); // NOI18N

        javax.swing.GroupLayout menuLaporanCutiLayout = new javax.swing.GroupLayout(menuLaporanCuti);
        menuLaporanCuti.setLayout(menuLaporanCutiLayout);
        menuLaporanCutiLayout.setHorizontalGroup(
            menuLaporanCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanCutiLayout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLaporanCutiLayout.setVerticalGroup(
            menuLaporanCutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLaporanCutiLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuLaporanResign.setBackground(new java.awt.Color(1, 113, 122));
        menuLaporanResign.setOpaque(false);
        menuLaporanResign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanResignMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Report Resign");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_circle.png"))); // NOI18N

        javax.swing.GroupLayout menuLaporanResignLayout = new javax.swing.GroupLayout(menuLaporanResign);
        menuLaporanResign.setLayout(menuLaporanResignLayout);
        menuLaporanResignLayout.setHorizontalGroup(
            menuLaporanResignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanResignLayout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLaporanResignLayout.setVerticalGroup(
            menuLaporanResignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_arrow_down.png"))); // NOI18N

        menuLaporanPayroll.setBackground(new java.awt.Color(1, 113, 122));
        menuLaporanPayroll.setOpaque(false);
        menuLaporanPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLaporanPayrollMouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Report Payroll");

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_circle.png"))); // NOI18N

        javax.swing.GroupLayout menuLaporanPayrollLayout = new javax.swing.GroupLayout(menuLaporanPayroll);
        menuLaporanPayroll.setLayout(menuLaporanPayrollLayout);
        menuLaporanPayrollLayout.setHorizontalGroup(
            menuLaporanPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLaporanPayrollLayout.createSequentialGroup()
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLaporanPayrollLayout.setVerticalGroup(
            menuLaporanPayrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout groupLaporanLayout = new javax.swing.GroupLayout(groupLaporan);
        groupLaporan.setLayout(groupLaporanLayout);
        groupLaporanLayout.setHorizontalGroup(
            groupLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupLaporanLayout.createSequentialGroup()
                .addGroup(groupLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupLaporanLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groupLaporanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(groupLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuLaporanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuLaporanCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuLaporanResign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuLaporanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuLaporanPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        groupLaporanLayout.setVerticalGroup(
            groupLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupLaporanLayout.createSequentialGroup()
                .addGroup(groupLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLaporanAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLaporanKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLaporanCuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLaporanResign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLaporanPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setText("Logout");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        menuAbsensi.setBackground(new java.awt.Color(0, 162, 161));
        menuAbsensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAbsensi.setOpaque(false);
        menuAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbsensiMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_home.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Absensi");

        javax.swing.GroupLayout menuAbsensiLayout = new javax.swing.GroupLayout(menuAbsensi);
        menuAbsensi.setLayout(menuAbsensiLayout);
        menuAbsensiLayout.setHorizontalGroup(
            menuAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAbsensiLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuAbsensiLayout.setVerticalGroup(
            menuAbsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuResign1.setBackground(new java.awt.Color(0, 162, 161));
        MenuResign1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuResign1.setOpaque(false);
        MenuResign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuResign1MouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sub.png"))); // NOI18N

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText(" Employee Assessment");

        javax.swing.GroupLayout MenuResign1Layout = new javax.swing.GroupLayout(MenuResign1);
        MenuResign1.setLayout(MenuResign1Layout);
        MenuResign1Layout.setHorizontalGroup(
            MenuResign1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuResign1Layout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuResign1Layout.setVerticalGroup(
            MenuResign1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuResign2.setBackground(new java.awt.Color(0, 162, 161));
        MenuResign2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuResign2.setOpaque(false);
        MenuResign2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuResign2MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_sub.png"))); // NOI18N

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Payroll");

        javax.swing.GroupLayout MenuResign2Layout = new javax.swing.GroupLayout(MenuResign2);
        MenuResign2.setLayout(MenuResign2Layout);
        MenuResign2Layout.setHorizontalGroup(
            MenuResign2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuResign2Layout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuResign2Layout.setVerticalGroup(
            MenuResign2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuLeave, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(MenuEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuResign, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(menuAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuResign1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(MenuResign2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(groupLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLeave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuResign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuResign1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuResign2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE))
        );

        panelMain.add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelWrapper.setBackground(new java.awt.Color(230, 244, 241));
        panelWrapper.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(241, 245, 249));
        jPanel3.setPreferredSize(new java.awt.Dimension(646, 115));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(241, 245, 249));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(241, 245, 249));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 746));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel6, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.BorderLayout());
        panelWrapper.add(panelContent, java.awt.BorderLayout.CENTER);

        panelMain.add(panelWrapper, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(962, 1018));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        panelContent.removeAll();
        if (roleName.toLowerCase().equals("user")) {
            panelContent.add(new MenuAbsensi(fullName, karyawan_id));
        } else {
            panelContent.add(new MenuAbsensi(fullName,karyawan_id));
        }

        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void MenuResign2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuResign2MouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuPayroll(karyawan_id, roleName));
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_MenuResign2MouseClicked

    private void MenuResign1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuResign1MouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuEmployeeAssesment());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_MenuResign1MouseClicked

    private void menuAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbsensiMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuAbsensi(fullName, karyawan_id));
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuAbsensiMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void groupLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupLaporanMouseClicked
        // TODO add your handling code here:
                menuLaporanAbsensi.setVisible(!menuLaporanAbsensi.isVisible());
                menuLaporanKaryawan.setVisible(!menuLaporanKaryawan.isVisible());
                menuLaporanCuti.setVisible(!menuLaporanCuti.isVisible());
                menuLaporanResign.setVisible(!menuLaporanResign.isVisible());
                menuLaporanPayroll.setVisible(!menuLaporanPayroll.isVisible());
    }//GEN-LAST:event_groupLaporanMouseClicked

    private void menuLaporanPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanPayrollMouseClicked
        // TODO add your handling code here:

        try {
            InputStream reportStream =
            getClass().getResourceAsStream("/Report/ReportPayroll.jasper");

            if (reportStream == null) {
                throw new RuntimeException("ReportAbsensi.jasper NOT FOUND");
            }

            JasperReport jasperReport =
            (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jasperPrint =
            JasperFillManager.fillReport(jasperReport, null, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace(); // VERY IMPORTANT while testing
        }
    }//GEN-LAST:event_menuLaporanPayrollMouseClicked

    private void menuLaporanResignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanResignMouseClicked
        // TODO add your handling code here:
        try {
            InputStream reportStream =
            getClass().getResourceAsStream("/Report/ReportResign.jasper");

            if (reportStream == null) {
                throw new RuntimeException("ReportAbsensi.jasper NOT FOUND");
            }

            JasperReport jasperReport =
            (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jasperPrint =
            JasperFillManager.fillReport(jasperReport, null, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace(); // VERY IMPORTANT while testing
        }
    }//GEN-LAST:event_menuLaporanResignMouseClicked

    private void menuLaporanCutiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanCutiMouseClicked
        try {
            InputStream reportStream =
            getClass().getResourceAsStream("/Report/ReportLeave.jasper");

            if (reportStream == null) {
                throw new RuntimeException("ReportAbsensi.jasper NOT FOUND");
            }

            JasperReport jasperReport =
            (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jasperPrint =
            JasperFillManager.fillReport(jasperReport, null, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace(); // VERY IMPORTANT while testing
        }
    }//GEN-LAST:event_menuLaporanCutiMouseClicked

    private void menuLaporanKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanKaryawanMouseClicked
        // TODO add your handling code here:
        try {
            InputStream reportStream =
            getClass().getResourceAsStream("/Report/ReportKaryawan.jasper");

            if (reportStream == null) {
                throw new RuntimeException("ReportAbsensi.jasper NOT FOUND");
            }

            JasperReport jasperReport =
            (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jasperPrint =
            JasperFillManager.fillReport(jasperReport, null, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace(); // VERY IMPORTANT while testing
        }
    }//GEN-LAST:event_menuLaporanKaryawanMouseClicked

    private void menuLaporanAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanAbsensiMouseClicked
        // TODO add your handling code here:
        try {
            InputStream reportStream =
            getClass().getResourceAsStream("/Report/ReportAbsensi.jasper");

            if (reportStream == null) {
                throw new RuntimeException("ReportAbsensi.jasper NOT FOUND");
            }

            JasperReport jasperReport =
            (JasperReport) JRLoader.loadObject(reportStream);

            JasperPrint jasperPrint =
            JasperFillManager.fillReport(jasperReport, null, conn);

            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setLocationRelativeTo(null);
            viewer.setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace(); // VERY IMPORTANT while testing
        }
    }//GEN-LAST:event_menuLaporanAbsensiMouseClicked

    private void MenuResignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuResignMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuResign(karyawan_id, roleName));
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_MenuResignMouseClicked

    private void MenuLeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLeaveMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuLeave(karyawan_id, roleName));
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_MenuLeaveMouseClicked

    private void MenuEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEmployeeMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new MenuEmployee());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_MenuEmployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuEmployee;
    private javax.swing.JPanel MenuLeave;
    private javax.swing.JPanel MenuResign;
    private javax.swing.JPanel MenuResign1;
    private javax.swing.JPanel MenuResign2;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel groupLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel menuAbsensi;
    private javax.swing.JPanel menuLaporanAbsensi;
    private javax.swing.JPanel menuLaporanCuti;
    private javax.swing.JPanel menuLaporanKaryawan;
    private javax.swing.JPanel menuLaporanPayroll;
    private javax.swing.JPanel menuLaporanResign;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelWrapper;
    // End of variables declaration//GEN-END:variables
}
